import {Aurora} from "../engine/aurora.js";
import {Camera} from "../engine/camera.js";
export class EgyptScene{
constructor(game){this.game=game;this.worldWidth=2200;this.aurora=new Aurora();this.camera=new Camera(game.width,this.worldWidth);this.stage=0;this.trap=false;this.door=false;this.lastHint=0}
enter(){this.game.dialogue.say("Vi tar det rolig. Se etter det som ikke passer inn.");this.obj("Finn inngangen","1 / 4")}
obj(t,p){document.getElementById("objective").textContent=t;document.getElementById("progress").textContent=p}
update(dt){this.aurora.update(dt,this.game.input,this.worldWidth);this.camera.viewWidth=this.game.width;this.camera.update(this.aurora.x);
if(this.stage===0&&this.aurora.x>620){this.stage=1;this.obj("Undersøk gulvet","2 / 4");this.game.dialogue.say("Vent litt. Den midterste steinen ligger lavere enn de andre.")}
if(this.stage===1&&this.game.input.consume("interact")){if(this.aurora.x<560||this.aurora.x>780){this.game.dialogue.say("Jeg må stå nærmere den slitte steinen.");return}this.trap=true;this.stage=2;this.obj("Finn den skjulte mekanismen","3 / 4");this.game.dialogue.say("En gammel trykkplate. Godt vi undersøkte før vi gikk videre.")}
if(this.stage===2&&this.aurora.x>1180&&this.game.input.consume("interact")){this.door=true;this.stage=3;this.obj("Gå inn i gravkammeret","4 / 4");this.game.dialogue.say("Der åpnet den seg. Ingen har sett dette rommet på svært lenge.")}
if(performance.now()-this.lastHint>10000){this.lastHint=performance.now();if(this.stage===0)this.game.dialogue.say("Se én gang til. Gulvet forteller oss mer enn veggene.");else if(this.stage===1)this.game.dialogue.say("Stå ved den slitte steinen og trykk UNDERSØK.");else if(this.stage===2)this.game.dialogue.say("Jeg ville sett nærmere på veggen lenger mot høyre.")}}
render(ctx,w,h){const floor=h*.72;ctx.clearRect(0,0,w,h);const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,"#5b412b");g.addColorStop(.7,"#211710");g.addColorStop(1,"#0c0805");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(-this.camera.x,0);ctx.fillStyle="#3f2e1e";ctx.fillRect(0,floor,this.worldWidth,h-floor);for(let x=0;x<this.worldWidth;x+=150){ctx.fillStyle=x%300===0?"#3a291b":"#2d2117";ctx.fillRect(x,floor-250,100,250)}ctx.fillStyle=this.trap?"#8b6336":"#5e4328";ctx.fillRect(640,floor-8,100,16);if(this.trap){ctx.strokeStyle="#bca27b";ctx.lineWidth=4;for(let i=0;i<4;i++){ctx.beginPath();ctx.moveTo(780+i*12,floor-120-i*15);ctx.lineTo(850+i*12,floor-90-i*15);ctx.stroke()}}ctx.fillStyle="#17110c";ctx.fillRect(1250,floor-260,190,260);ctx.strokeStyle="#77593a";ctx.lineWidth=10;ctx.strokeRect(1250,floor-260,190,260);ctx.fillStyle=this.door?"rgba(215,179,107,.18)":"#4a3522";ctx.fillRect(1260,floor-250,170,250);this.aurora.render(ctx,this.aurora.x,floor);ctx.restore()}
}
